<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<groupId>com.xunjia</groupId>
	<artifactId>xunjia-framework2-parent</artifactId>
	<version>2.0.0</version>
	<packaging>pom</packaging>
	<name>PES</name>
	<description>xunjia develop framework parent jar</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<build.plugins.plugin.version>3.1</build.plugins.plugin.version>
		<org.springframework.boot.version>2.3.0.RELEASE</org.springframework.boot.version>
		<elasticsearch.version>7.11.1</elasticsearch.version>
		<framework.version>2.0.0</framework.version>
	</properties>
	
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.0.RELEASE</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<modules>
		<module>xunjia-framework2-static</module>
		<module>xunjia-framework2-common</module>
		<module>xunjia-framework2-develop</module>
		<module>xunjia-framework2-usermanage</module>
		<module>xunjia-framework2-app</module>
		<module>xunjia-framework2-utils</module>
		<module>xunjia-framework2-common-modules</module>
		<module>xunjia-framework2-core</module>
		<module>xunjia-framework2-log</module>
        <module>pes-data-sync</module>
		<module>pes-app-core</module>
		<module>xunjia-framework2-system</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter</artifactId>
				<version>${org.springframework.boot.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-data-jpa</artifactId>
				<version>${org.springframework.boot.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-thymeleaf</artifactId>
				<version>${org.springframework.boot.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-web</artifactId>
				<version>${org.springframework.boot.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-devtools</artifactId>
				<scope>runtime</scope>
				<optional>true</optional>
				<version>${org.springframework.boot.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-configuration-processor</artifactId>
				<optional>true</optional>
				<version>${org.springframework.boot.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-test</artifactId>
				<scope>test</scope>
				<version>${org.springframework.boot.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-actuator</artifactId>
			</dependency>
			<dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<scope>runtime</scope>
				<version>8.0.20</version>
			</dependency>
			<dependency>
				<groupId>com.alibaba</groupId>
				<artifactId>druid-spring-boot-starter</artifactId>
				<version>1.1.21</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<optional>true</optional>
				<version>1.18.12</version>
			</dependency>
			<dependency>
				<groupId>com.belerweb</groupId>
				<artifactId>pinyin4j</artifactId>
				<version>2.5.1</version>
			</dependency>
			<dependency>
				<groupId>org.elasticsearch</groupId>
				<artifactId>elasticsearch</artifactId>
				<version>${elasticsearch.version}</version>
			</dependency>
			<dependency>
				<groupId>org.elasticsearch.client</groupId>
				<artifactId>elasticsearch-rest-client</artifactId>
				<version>${elasticsearch.version}</version>
			</dependency>
			<dependency>
				<groupId>org.elasticsearch.client</groupId>
				<artifactId>elasticsearch-rest-high-level-client</artifactId>
				<version>${elasticsearch.version}</version>
			</dependency>

			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-core</artifactId>
				<version>${framework.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-common</artifactId>
				<version>${framework.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-common-modules</artifactId>
				<version>${framework.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-develop</artifactId>
				<version>${framework.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-log</artifactId>
				<version>${framework.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-static</artifactId>
				<version>${framework.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-system</artifactId>
				<version>${framework.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-utils</artifactId>
				<version>${framework.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-workflow</artifactId>
				<version>${framework.version}</version>
			</dependency>
			<dependency>
				<groupId>com.xunjia</groupId>
				<artifactId>xunjia-framework2-usermanage</artifactId>
				<version>${framework.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${build.plugins.plugin.version}</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
